FROM ubuntu:14.04
MAINTAINER Dan Villiom Podlaski Christiansen <dan@magenta.dk>

# initial config
ENV DEBIAN_FRONTEND=noninteractive
ENV deps="python python-setuptools libxmlsec1-openssl postgresql-client ca-certificates"
ENV build_deps="python-pip libxmlsec1-dev devscripts equivs"
ENV source_packages="psycopg2 m2crypto"

# ensure the box is up-to-date
RUN apt-get -qqy update
RUN apt-get -qqy dist-upgrade

# now install the basic dependancies
RUN apt-get -qqy install --no-install-recommends \
            $deps $build_deps

# the source_packages are python modules with a lot of build
# dependancies. we install these using a package generated by
# mk-build-deps, and mark it as automatically installed -- this way,
# we can easily uninstall all the dependancies
RUN cd /tmp; \
    for pkg in $source_packages; do \
      mk-build-deps $pkg; \
      dpkg -i $pkg-build-deps_*.deb || apt-get -qqy install -f; \
      apt-mark markauto $pkg-build-deps; \
      rm -v $pkg-build-deps_*.deb; \
    done

# copy the sources into place
COPY oio_rest /srv/mox/oio_rest

# now build & install all our python dependancies
RUN python /srv/mox/oio_rest/setup.py develop

# install gunicorn for serving the WSGI app
RUN pip -q install gunicorn gevent setproctitle

# cleanup
RUN apt-get -qy purge --auto-remove $build_deps

# add a 'mox' user
RUN useradd --home-dir /srv/mox mox
RUN install -d -o mox -g mox /var/log/oio_rest /var/run/oio_rest

# gunicorn takes the wsgi script as an importable python module
RUN ln -s server-setup/oio_rest.wsgi /srv/mox/oio_rest/oio_wsgi.py

# runtime config for gunicorn
WORKDIR /srv/mox/oio_rest
CMD [ "/usr/local/bin/gunicorn", \
      "-c", "server-setup/gunicorn-config.py", "oio_wsgi" ]

EXPOSE 8000
